/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import DAO.JuegoDAO;
import POJO.CategoriasPOJO;
import POJO.PreguntasPOJO;
import POJO.RespuestasPOJO;
import POJO.UsuariosPOJO;
import java.util.ArrayList;

/**
 *
 * @author JEAR
 */
public class JuegoPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JuegoPrincipal
     */
    public static int nivel = 1;
     public static int preguntaBuscar;
      static int puntaje=0;
     public static String nombre;
     public static String estado;
     
    ArrayList<CategoriasPOJO> listacategorias;
    ArrayList<PreguntasPOJO> listaPreguntas;
    ArrayList<RespuestasPOJO> listaRespuestas;
    
    public JuegoPrincipal() {
        initComponents();
        traerPreguntas();
        traerRespuestas();
         traerCategorias();
         inicio ini = new inicio();
         nombre=ini.nombre;
         nombreJugador.setText(nombre);
         puntos.setText(String.valueOf(puntaje));
         nivelJuego.setText(String.valueOf(nivel));
    }
    
     public void traerPreguntas(){
        try{            
            JuegoDAO metodos = new JuegoDAO();
            listaPreguntas = metodos.listaPreguntas(nivel);
            int valor = (int)(Math.random()*listaPreguntas.size());
            if(valor==0){
                valor=1;
            }
            preguntas.setText(listaPreguntas.get(valor).getPregunta());
            preguntaBuscar = listaPreguntas.get(valor).getId();
        }catch(Exception e){
        }
    }
    
    public void traerRespuestas(){
        try{
            JuegoDAO metodos = new JuegoDAO();
            listaRespuestas = metodos.listaRespuestas(preguntaBuscar);
            opcion1.setText(listaRespuestas.get(0).getRespuesta());
            opcion2.setText(listaRespuestas.get(1).getRespuesta());
            opcion3.setText(listaRespuestas.get(2).getRespuesta());
            opcion4.setText(listaRespuestas.get(3).getRespuesta());
            
        }catch(Exception e){            
        }
    }
     public void traerCategorias(){
        try{
            JuegoDAO metodos = new JuegoDAO();
            listacategorias = metodos.listaCategorias();
            categoria.setText(listacategorias.get(nivel-1).getCategoria());
            
        }catch(Exception e){            
        }
    }
    
    public void comprobarRespuesta(){
            
            if(nivel<5){
                puntaje = puntaje*nivel+100;
                nivel = nivel+1;
                traerPreguntas();
                traerRespuestas();
                nivelJuego.setText(String.valueOf(nivel));
                puntos.setText(String.valueOf(puntaje));
                traerCategorias();
            }else{
                estado = "Gano";
                guardarHistorico();
                nivel = 1;
                String[] args = null;
                gana.main(args);
                dispose();
            }  
    }
    
     public void guardarHistorico(){
        inicio ini = new inicio();
        UsuariosPOJO usuario = new UsuariosPOJO();
        usuario.setNombre(ini.nombre);
        usuario.setNivel(nivel);
        usuario.setPuntaje(puntaje);
        usuario.setEstado(estado);
          
        try{
           JuegoDAO metodos = new JuegoDAO();
            metodos.historico(usuario);
        }catch(Exception e){
            
        }
    }
     public void juegoPerdido(){
        estado = "Perdio";        
        puntaje = 0;
        guardarHistorico();
        nivel = 1;
        pierde.main(null);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcion1 = new javax.swing.JButton();
        opcion2 = new javax.swing.JButton();
        opcion3 = new javax.swing.JButton();
        opcion4 = new javax.swing.JButton();
        preguntas = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nombreJugador = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        categoria = new javax.swing.JLabel();
        puntos = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nivelJuego = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        opcion1.setText("jButton1");
        opcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion1ActionPerformed(evt);
            }
        });

        opcion2.setText("jButton2");
        opcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion2ActionPerformed(evt);
            }
        });

        opcion3.setText("jButton3");
        opcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion3ActionPerformed(evt);
            }
        });

        opcion4.setText("jButton4");
        opcion4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion4ActionPerformed(evt);
            }
        });

        preguntas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        preguntas.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setText("JUGADOR: ");

        nombreJugador.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        nombreJugador.setText("jLabel2");

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setText("CATEGORIA: ");

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setText("PUNTOS:");

        categoria.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        categoria.setText("jLabel2");

        puntos.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        puntos.setText("jLabel2");

        jButton1.setText("Retirarse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel4.setText("NIVEL:");

        nivelJuego.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        nivelJuego.setText("jLabel2");

        jLabel5.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jLabel5.setText("PREGUNTA: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombreJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(puntos, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(62, 62, 62))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(preguntas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(358, 358, 358))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(opcion1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                    .addComponent(opcion3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(opcion2, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                    .addComponent(opcion4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel4)
                                .addGap(30, 30, 30)
                                .addComponent(nivelJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombreJugador)
                    .addComponent(jLabel3)
                    .addComponent(puntos)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(categoria)
                    .addComponent(jLabel4)
                    .addComponent(nivelJuego))
                .addGap(40, 40, 40)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(preguntas, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opcion2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(opcion4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opcion3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion1ActionPerformed
        System.out.println("resp " +listaRespuestas.get(0).getValor()); 
        for(int k=0;k<listaRespuestas.size();k++){
             System.out.println("resp " +listaRespuestas.get(k).getValor());
        }
        if (listaRespuestas.get(0).getValor()==1) {
             System.out.println("resp " +listaRespuestas.get(0).getValor());
            comprobarRespuesta();       
        }else{
            juegoPerdido();
        }
    }//GEN-LAST:event_opcion1ActionPerformed

    private void opcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion3ActionPerformed
        System.out.println("resp " +listaRespuestas.get(1).getValor());
        if (listaRespuestas.get(2).getValor()==1) {
            comprobarRespuesta();       
        }else{
            juegoPerdido();
        }
    }//GEN-LAST:event_opcion3ActionPerformed

    private void opcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion2ActionPerformed
        System.out.println("resp " +listaRespuestas.get(2).getValor());
        if (listaRespuestas.get(1).getValor()==1) {
            comprobarRespuesta();       
        }else{
            juegoPerdido();
        }
    }//GEN-LAST:event_opcion2ActionPerformed

    private void opcion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion4ActionPerformed
        System.out.println("resp " +listaRespuestas.get(3).getValor()); 
        if (listaRespuestas.get(3).getValor()==1) {
            comprobarRespuesta();       
        }else{
            juegoPerdido();
        }
    }//GEN-LAST:event_opcion4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       estado = "Abandono";
        
        guardarHistorico();
        
        nivel = 1;
        String[] args = null;
        retiro.main(args);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuegoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuegoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuegoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuegoPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JuegoPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel categoria;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel nivelJuego;
    private javax.swing.JLabel nombreJugador;
    private javax.swing.JButton opcion1;
    private javax.swing.JButton opcion2;
    private javax.swing.JButton opcion3;
    private javax.swing.JButton opcion4;
    private javax.swing.JLabel preguntas;
    private javax.swing.JLabel puntos;
    // End of variables declaration//GEN-END:variables
}
